### ISSUE TITLE
Waiting for the open-source and updating Arxiv pre-print

### ISSUE THREAD

**Issue by Lupin1998** [shashankvkt/AlignMixup_CVPR22#1]
Hi authors,
Thanks for your great work. I have noticed AlignMix since last year and have some questions about image classification results on ImageNet-1k. I notice that AlignMix reports top-1 accuracy of 81.17 on ImageNet-1k based on ResNet-50 training 300 epochs, but this repo reports 79.32. Why? I am looking forward to the open-source and new pre-print.

**Comment by shashankvkt** [comment]
Hi,
Thank you for your interest in our work. The paper on arxiv is quite outdated (last update 29th March' 21) and has gone through some revisions for CVPR'22. We will update arxiv by tomorrow and then release the source-code after that. The results reported in this repo is correct. Thank you for your patience.
