### ISSUE TITLE
Align Mixup Interpolation & Alignment Part

### ISSUE THREAD

**Issue by DuyguSerbes** [shashankvkt/AlignMixup_CVPR22#2]
Thanks for your contributions to the literature.

Does the code include only mixup? I cannot find the encoder part unfortunately.

**Comment by shashankvkt** [comment]
Thanks for your interest in our work.  
No, the alignment part along with its interpolation is defined at https://github.com/shashankvkt/AlignMixup_CVPR22/blob/ec01a689b56ad4f65948ea17c16a31f651a3f1c3/cifar10_100/models/resnet18_classifier.py#L20

**Comment by DuyguSerbes** [comment]
Thank you very much! :)
